'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck } from 'lucide-react';
import { trackEvent } from './funnel';
const initial = { city:'', state:'', average_home_price:'', target_buyer_type:[], target_price_range:'', target_areas:'', current_acquisition_methods:[], current_monthly_buyer_volume:'', currently_running_ads:'', monthly_ad_budget:'', first_name:'', email:'', brokerage:'', phone:'', marketing_consent:false, website:'' };
const steps = ['Market & buyer', 'Current acquisition', 'Contact'];
const methods = ['Referrals & open houses','Lead platforms','Meta / Facebook Ads','Google Ads','Social media','Prospecting',"No consistent system",'Other'];
export default function AuditForm() {
 const [step,setStep]=useState(0),[form,setForm]=useState(initial),[error,setError]=useState(''),[sending,setSending]=useState(false),[done,setDone]=useState(false);
 const started=useRef(false), heading=useRef(null);
 useEffect(()=>{trackEvent('audit_view');},[]);
 useEffect(()=>{if(step>0) heading.current?.focus();},[step]);
 const set=(key,value)=>{if(!started.current){trackEvent('audit_start');started.current=true;}setForm(f=>({...f,[key]:value}));};
 const toggle=(value)=>set('current_acquisition_methods',form.current_acquisition_methods.includes(value)?form.current_acquisition_methods.filter(x=>x!==value):[...form.current_acquisition_methods,value]);
 function validate(){
  if(step===0&&(!form.city.trim()||!form.state.trim()||!form.target_price_range.trim()||!form.target_buyer_type.length))return 'Enter your city, state, buyer price range and buyer type.';
  if(step===1&&(!form.current_acquisition_methods.length||!form.currently_running_ads))return 'Select your acquisition methods and whether you currently run ads.';
  if(step===2&&(!form.first_name.trim()||!/^\S+@\S+\.\S+$/.test(form.email.trim())))return 'Enter your first name and a valid email address.';
  return '';
 }
 function next(){const message=validate();if(message){setError(message);return;}trackEvent('audit_step',step===0?'market':'acquisition');setError('');setStep(step+1);}
 async function submit(e){e.preventDefault();if(step<2){next();return;}const message=validate();if(message){setError(message);return;}setSending(true);setError('');try{const response=await fetch('/api/audit/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,average_home_price:form.target_price_range,target_areas:form.city})});const data=await response.json();if(!response.ok)throw Error(data.error||'Submission failed.');trackEvent('audit_submitted');setDone(true);}catch(err){setError(err.message||'Please try again.');}finally{setSending(false);}}
 if(done)return <div className="audit-success" role="status"><CheckCircle2 size={40}/><h2>Your audit request is in.</h2><p>We’ll review your answers and send your personalized audit to <strong>{form.email}</strong>. If we need more context, we’ll email you first.</p><p>Delivery timing will be confirmed after review. You haven’t signed up for a paid service.</p><a className="btn secondary" href="https://calendly.com/mansur-adlift/30min" target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent('call_click')}>Want to discuss it? Book a call <ArrowRight size={17}/></a></div>;
 return <form className="audit-form" onSubmit={submit} noValidate>
 <div className="audit-progress-head"><span>Step {step+1} of 3</span><strong>{steps[step]}</strong></div><div className="audit-progress"><i style={{width:`${(step+1)/3*100}%`}}/></div>
 <div className="audit-step"><h2 ref={heading} tabIndex={-1}>{['Who do you want to reach?','What’s your current setup?','Where should we send the audit?'][step]}</h2>
 {step===0&&<><p>Give us the essentials. More detail can come later.</p><div className="form-pair"><label>City / primary market<input required autoComplete="address-level2" value={form.city} onChange={e=>set('city',e.target.value)} placeholder="e.g. Miami" maxLength={100}/></label><label>State<input required autoComplete="address-level1" value={form.state} onChange={e=>set('state',e.target.value)} placeholder="e.g. Florida" maxLength={100}/></label></div><label>Buyer price range<input required value={form.target_price_range} onChange={e=>set('target_price_range',e.target.value)} placeholder="e.g. $350k–$550k" maxLength={100}/></label><label>Buyer type<select required value={form.target_buyer_type[0]||''} onChange={e=>set('target_buyer_type',e.target.value?[e.target.value]:[])}><option value="">Select a buyer profile</option>{['First-time buyers','Move-up buyers','Luxury buyers','Investors','Relocation buyers','General buyers','Other'].map(x=><option key={x}>{x}</option>)}</select></label></>}
 {step===1&&<><fieldset><legend>How do you get buyer inquiries? Select all that apply.</legend><div className="choice-grid">{methods.map(x=><button type="button" aria-pressed={form.current_acquisition_methods.includes(x)} className={form.current_acquisition_methods.includes(x)?'choice active':'choice'} key={x} onClick={()=>toggle(x)}>{x}</button>)}</div></fieldset><fieldset><legend>Are you currently running paid ads?</legend><div className="choice-grid two">{['Yes','No'].map(x=><button type="button" aria-pressed={form.currently_running_ads===x} className={form.currently_running_ads===x?'choice active':'choice'} key={x} onClick={()=>set('currently_running_ads',x)}>{x}</button>)}</div></fieldset><label>Monthly ad budget <small>Optional</small><input value={form.monthly_ad_budget} onChange={e=>set('monthly_ad_budget',e.target.value)} placeholder="e.g. $0, $500 or not sure yet" maxLength={50}/></label></>}
 {step===2&&<><label>First name<input required autoComplete="given-name" value={form.first_name} onChange={e=>set('first_name',e.target.value)} maxLength={80}/></label><label>Business email<input required type="email" autoComplete="email" value={form.email} onChange={e=>set('email',e.target.value)} maxLength={200}/></label><label>Brokerage / team <small>Optional</small><input value={form.brokerage} onChange={e=>set('brokerage',e.target.value)} maxLength={150}/></label><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>set('website',e.target.value)}/></label><label className="consent"><input type="checkbox" checked={form.marketing_consent} onChange={e=>set('marketing_consent',e.target.checked)}/><span>Send me occasional AdLift marketing emails too. Optional.</span></label><p className="audit-privacy"><ShieldCheck size={16}/>We use your answers to prepare and email your audit, and to follow up about it. Marketing emails are optional.</p><p className="audit-note">No payment required. Delivery timing is confirmed by email after review.</p></>}
 </div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="audit-actions">{step>0&&<button className="btn secondary" type="button" onClick={()=>{setError('');setStep(step-1);}}><ArrowLeft size={17}/>Back</button>}{step<2?<button key="continue" className="btn primary" type="button" onClick={e=>{e.preventDefault();next();}}>Continue <ArrowRight size={17}/></button>:<button key="submit" className="btn primary" type="submit" disabled={sending}>{sending?'Sending…':'Request my free audit'}<ArrowRight size={17}/></button>}</div>
 </form>;
}
