'use client';

import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck } from 'lucide-react';

const buyerTypes = ['First-time buyers','Move-up buyers','Luxury buyers','Investors','Relocation buyers','General buyers','Other'];
const acquisitionMethods = ['Referrals','Zillow/Realtor.com','Meta/Facebook Ads','Google Ads','Social media','Cold calling/prospecting','Open houses','Purchased leads','Other',"I don't have a consistent system"];
const initial = { city:'', state:'', average_home_price:'', target_buyer_type:[], target_price_range:'', target_areas:'', current_acquisition_methods:[], current_monthly_buyer_volume:'', currently_running_ads:'', monthly_ad_budget:'', first_name:'', email:'', brokerage:'', phone:'', marketing_consent:false, website:'' };

export default function AuditForm(){
  const [step,setStep]=useState(0); const [form,setForm]=useState(initial); const [error,setError]=useState(''); const [sending,setSending]=useState(false); const [done,setDone]=useState(false);
  const steps=['Market','Ideal Buyer','Current Acquisition','Advertising','Contact'];
  const progress=useMemo(()=>((step+1)/steps.length)*100,[step]);
  const set=(key,value)=>setForm(v=>({...v,[key]:value}));
  const toggle=(key,value)=>setForm(v=>({...v,[key]:v[key].includes(value)?v[key].filter(x=>x!==value):[...v[key],value]}));
  function validate(){
    if(step===0 && (!form.city.trim()||!form.state.trim()||!form.average_home_price.trim())) return 'Complete your market details to continue.';
    if(step===1 && (!form.target_buyer_type.length||!form.target_price_range.trim()||!form.target_areas.trim())) return 'Tell us who you want to attract and where.';
    if(step===2 && (!form.current_acquisition_methods.length||!form.current_monthly_buyer_volume.trim())) return 'Complete your current acquisition details.';
    if(step===3 && (!form.currently_running_ads||!form.monthly_ad_budget.trim())) return 'Complete the advertising questions. A $0 budget is completely fine.';
    if(step===4 && (!form.first_name.trim()||!/^\S+@\S+\.\S+$/.test(form.email))) return 'Enter your first name and a valid email address.';
    return '';
  }
  function next(){const e=validate(); if(e){setError(e);return;} setError(''); setStep(s=>Math.min(s+1,4));}
  async function submit(e){e.preventDefault(); const v=validate(); if(v){setError(v);return;} setSending(true);setError(''); try{const r=await fetch('/api/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Submission failed'); setDone(true);}catch(err){setError(err.message||'Something went wrong. Please try again.');}finally{setSending(false);}}
  if(done) return <div className="audit-success"><CheckCircle2 size={44}/><p className="eyebrow">Request received</p><h2>Your Buyer Acquisition Audit Request Is In</h2><p>We’ve received your information and will prepare a personalized breakdown of how a buyer acquisition campaign could be structured for your market.</p><div className="audit-cover"><span>Suggested buyer targeting</span><span>Potential campaign / offer angle</span><span>Recommended qualification criteria</span><span>Suggested buyer funnel</span><span>Acquisition opportunities and weaknesses</span><span>How AdLift could potentially implement the system</span></div><p className="audit-note">We won’t invent market statistics, lead volumes, ROAS or revenue projections. Recommendations are based on the information you submitted.</p><a className="btn primary large" href="https://calendly.com/mansur-adlift/30min?back=1&month=2025-11&date=2025-11-24" target="_blank" rel="noopener noreferrer">Discuss your strategy now <ArrowRight size={18}/></a></div>;
  return <form className="audit-form" onSubmit={submit} noValidate>
    <div className="audit-progress-head"><span>Step {step+1} of 5</span><strong>{steps[step]}</strong></div><div className="audit-progress"><i style={{width:`${progress}%`}}/></div>
    {step===0 && <div className="audit-step"><h2>Tell us about your market.</h2><p>This gives us the context for your personalized audit.</p><label>City / primary market<input value={form.city} onChange={e=>set('city',e.target.value)} placeholder="e.g. Austin" maxLength={100}/></label><label>State<input value={form.state} onChange={e=>set('state',e.target.value)} placeholder="e.g. Texas" maxLength={100}/></label><label>Average home price or typical buyer price range<input value={form.average_home_price} onChange={e=>set('average_home_price',e.target.value)} placeholder="e.g. $450k–$700k" maxLength={100}/></label></div>}
    {step===1 && <div className="audit-step"><h2>Who is your ideal buyer?</h2><p>Select every buyer type that fits.</p><fieldset><legend>Buyer type</legend><div className="choice-grid">{buyerTypes.map(x=><button type="button" className={form.target_buyer_type.includes(x)?'choice active':'choice'} onClick={()=>toggle('target_buyer_type',x)} key={x}>{x}</button>)}</div></fieldset><label>Preferred buyer price range<input value={form.target_price_range} onChange={e=>set('target_price_range',e.target.value)} placeholder="e.g. $500k–$850k" maxLength={100}/></label><label>Areas / neighborhoods<textarea value={form.target_areas} onChange={e=>set('target_areas',e.target.value)} placeholder="Cities, ZIP codes or neighborhoods" maxLength={500}/></label></div>}
    {step===2 && <div className="audit-step"><h2>How are you getting buyer clients now?</h2><fieldset><legend>Current acquisition methods</legend><div className="choice-grid">{acquisitionMethods.map(x=><button type="button" className={form.current_acquisition_methods.includes(x)?'choice active':'choice'} onClick={()=>toggle('current_acquisition_methods',x)} key={x}>{x}</button>)}</div></fieldset><label>Approx. new buyer clients / appointments per month<input value={form.current_monthly_buyer_volume} onChange={e=>set('current_monthly_buyer_volume',e.target.value)} placeholder="e.g. 2–4" maxLength={50}/></label></div>}
    {step===3 && <div className="audit-step"><h2>What does paid acquisition look like today?</h2><fieldset><legend>Are you currently running paid advertising?</legend><div className="choice-grid two">{['Yes','No'].map(x=><button type="button" className={form.currently_running_ads===x?'choice active':'choice'} onClick={()=>set('currently_running_ads',x)} key={x}>{x}</button>)}</div></fieldset><label>Approximate monthly advertising budget<input value={form.monthly_ad_budget} onChange={e=>set('monthly_ad_budget',e.target.value)} placeholder="e.g. $0, $500, $2,000" maxLength={50}/></label><p className="audit-note">Spending $0 does not disqualify you. The audit is meant to show what a sensible structure could look like.</p></div>}
    {step===4 && <div className="audit-step"><h2>Where should we send your audit?</h2><label>First name<input value={form.first_name} onChange={e=>set('first_name',e.target.value)} autoComplete="given-name" maxLength={80}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} autoComplete="email" maxLength={200}/></label><label>Brokerage / team <small>Optional</small><input value={form.brokerage} onChange={e=>set('brokerage',e.target.value)} maxLength={150}/></label><label>Phone <small>Optional</small><input value={form.phone} onChange={e=>set('phone',e.target.value)} autoComplete="tel" maxLength={40}/></label><label className="honeypot" aria-hidden="true">Website<input tabIndex="-1" autoComplete="off" value={form.website} onChange={e=>set('website',e.target.value)}/></label><label className="consent"><input type="checkbox" checked={form.marketing_consent} onChange={e=>set('marketing_consent',e.target.checked)}/><span>I’d also like to receive occasional AdLift marketing emails. Optional and not required to receive the audit.</span></label><p className="audit-privacy"><ShieldCheck size={16}/> By submitting, you ask AdLift to use the information above to prepare and contact you about this audit. Marketing consent is optional and is not pre-checked.</p></div>}
    {error && <p className="form-error" role="alert">{error}</p>}
    <div className="audit-actions">{step>0&&<button className="btn secondary" type="button" onClick={()=>{setError('');setStep(s=>s-1)}}><ArrowLeft size={17}/> Back</button>}{step<4?<button className="btn primary" type="button" onClick={next}>Next <ArrowRight size={17}/></button>:<button className="btn primary" disabled={sending} type="submit">{sending?'Submitting…':'Get my free audit'} <ArrowRight size={17}/></button>}</div>
  </form>;
}
