'use client';

import { useEffect } from 'react';
import { ArrowRight, CheckCircle2, Target, PhoneCall, CalendarCheck } from 'lucide-react';
import BuyerWorkflowDemo from './BuyerWorkflowDemo';
import { trackEvent } from './funnel';

const callUrl = 'https://calendly.com/mansur-adlift/30min';
function AuditCTA({ label = 'Get Your Free Buyer Acquisition Audit', source = 'homepage' }) {
  return <a className="btn primary" href="/audit/" onClick={() => trackEvent('audit_click', source)}>{label}<ArrowRight size={18}/></a>;
}
const faqs = [
  ['What will my free audit include?', 'A personalized review of your market and buyer profile, a suggested campaign angle, qualification criteria and a practical follow-up workflow. It is a strategy review, not a promise of lead volume or sales.'],
  ['How do I receive the audit?', 'We review your answers and send the audit to the email you provide. If we need more context, we’ll contact you there first. Turnaround is confirmed by email after review; there is no fixed delivery deadline advertised.'],
  ['How does the paid service work?', 'AdLift builds Meta campaigns, follows up with buyer inquiries, reviews them against agreed qualification criteria and schedules introductions with buyers who fit. Your audit is free and does not commit you to the paid service.'],
  ['Is advertising spend included?', 'Advertising spend and AdLift’s service fee are separate costs. The campaign budget and who funds it must be agreed before launch. Billing after agreed service delivery refers to AdLift’s service fee; it does not mean Meta advertising is free.'],
  ['What counts as a delivered appointment?', 'Before starting, we agree in writing on buyer criteria, appointment confirmation and what counts as delivery. The same agreement sets out how cancellations, no-shows and buyers outside the criteria are handled. No automatic replacement or refund policy is promised here.'],
  ['Does a booked appointment guarantee a sale?', 'No. Buyer fit and a confirmed appointment do not guarantee attendance, financing approval or a closed transaction.'],
  ['Do I need a long-term contract?', 'AdLift’s offer has no long-term lock-in. Scope, budget, fees and delivery terms are agreed before any paid work begins.'],
];

export default function Site() {
 useEffect(() => { trackEvent("homepage_view", "homepage"); }, []);
 return <main className="conversion-home">
  <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
  <header className="nav"><a className="logo" href="/" aria-label="AdLift home"><img className="brand-logo" src="/adlift-icon.png" alt="AdLift"/></a><nav aria-label="Primary navigation"><a href="#process">How it works</a><a href="#sample-audit">Sample audit</a><a href="#faq">FAQ</a></nav><a className="nav-cta" href="/audit/" onClick={()=>trackEvent('audit_click','navigation')}>Get free audit</a></header>
  <section className="hero" id="top">
   <div className="hero-copy"><p className="eyebrow">For U.S. real estate agents & small teams</p><h1>Less chasing.<br/>More qualified buyer conversations.</h1><p className="hero-sub">AdLift handles Meta Ads, manual buyer qualification and appointment scheduling—so you can focus on buyers who fit your criteria.</p><div className="cta-row"><AuditCTA source="hero"/><a className="btn secondary" href={callUrl} target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent('call_click','hero')}>Prefer to talk? Book a call</a></div><p className="hero-audit-note">Your free audit outlines a campaign angle, buyer criteria and follow-up plan for your market.</p><div className="trust-strip"><span><CheckCircle2 size={16}/>Manually qualified buyers</span><span><CheckCircle2 size={16}/>No long-term lock-in</span><span><CheckCircle2 size={16}/>Service fee after agreed delivery</span></div></div>
   <div className="hero-panel hero-outcome"><p className="mini-label">What you’re working toward</p><h2>A buyer conversation with context.</h2><p>Before an introduction, establish:</p><ul>{['Where they want to buy','Budget and financing readiness','Buying timeline','Whether they already have an agent','An agreed appointment time'].map(x=><li key={x}><CheckCircle2 size={18}/>{x}</li>)}</ul><a href="#qualification">Explore the qualification example <ArrowRight size={17}/></a><p className="demo-note">Criteria are agreed with you. Appointments do not guarantee sales.</p></div>
  </section>
  <section id="process" className="section compact-process"><div className="section-header"><p className="eyebrow">How it works</p><h2>You handle the buyer conversation.<br/>We handle the steps before it.</h2></div><div className="service-steps">{[[Target,'Attract buyer inquiries','Meta campaigns introduce a relevant offer in your market and collect useful buyer information.'],[PhoneCall,'Establish fit','We contact inquiries and review budget, location, timeline and representation against your criteria.'],[CalendarCheck,'Arrange the introduction','Buyers who fit and agree to a time are booked, with qualification notes ready for your conversation.']].map(([Icon,title,body],i)=><article key={title}><span className="service-step-number">0{i+1}</span><Icon size={24}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <BuyerWorkflowDemo/>
  <section id="sample-audit" className="section sample-audit-section"><div className="sample-audit-copy"><p className="eyebrow">Preview your free audit</p><h2>A practical plan for your market.</h2><p>See the kind of recommendations you can expect before deciding whether to work with AdLift.</p><ul><li>A campaign angle suited to your buyer profile</li><li>Criteria that separate inquiries from suitable buyers</li><li>A follow-up and appointment handoff plan</li></ul><AuditCTA source="sample_audit"/><p className="demo-note">Prepared after reviewing your answers and sent by email. Timing is confirmed after review.</p></div><article className="sample-report" aria-label="Illustrative buyer acquisition audit"><div className="sample-report-top"><span>ADLIFT / SAMPLE AUDIT</span><span>Illustrative · Not a client report</span></div><h3>Miami buyer acquisition plan</h3><p className="sample-assumption">Example inputs: single-family buyers · around $450k · buying within 90 days · inquiries currently followed up inconsistently.</p><ol><li><strong>Campaign angle</strong><p>Offer a buyer consultation on planning a Miami home search. Use accurate local information and a clear next step.</p></li><li><strong>Qualification checklist</strong><p>Confirm area, budget, timeline, financing status and existing representation. Discuss self-reported information before marking fit.</p></li><li><strong>Follow-up improvement</strong><p>Assign an owner to each new inquiry. Record contact attempts, answers and the next action rather than forwarding every form fill.</p></li><li><strong>Appointment handoff</strong><p>Agree a time with the buyer. Send the agent qualification notes, the buyer’s questions and the appointment details.</p></li></ol><div className="sample-report-bottom">First priority: establish consistent follow-up and qualification before increasing ad spend.</div><p className="demo-note">An example strategy, not market research or a forecast. Actual recommendations depend on your answers. Housing campaign settings must follow applicable advertising requirements.</p></article></section>
  <section className="section offer-terms"><div className="section-header"><p className="eyebrow">Clear terms before launch</p><h2>Know what you’re agreeing to.</h2><p>Your free audit comes first. Paid work begins only after scope, budget and delivery terms are agreed.</p></div><div className="terms-columns"><article><h3>Two separate costs</h3><p>Meta advertising spend is separate from AdLift’s service fee. The ad budget and funding arrangements are agreed before launch.</p></article><article><h3>Defined delivery</h3><p>We agree on qualification criteria, confirmation and how cancellations or no-shows are handled. AdLift’s service fee is billed after agreed delivery.</p></article><article><h3>A choice, not a commitment</h3><p>Requesting an audit does not enroll you in a paid service. Review the recommendations and decide whether a conversation makes sense.</p></article></div></section>
  <section id="faq" className="section faq-section"><div className="section-header"><p className="eyebrow">Questions before you start</p><h2>What should you expect?</h2></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section id="contact" className="section contact-section"><div className="contact-card"><div><p className="eyebrow">Your next step</p><h2>See the plan for your market.</h2><p>Tell us who you want to reach and how you acquire buyers today. We’ll review your setup and email a personalized audit.</p></div><AuditCTA source="final"/></div><a className="quiet-call" href={callUrl} target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent('call_click','final')}>Already have questions? Book a discovery call <ArrowRight size={16}/></a></section>
  <footer><div className="logo"><span>Ad</span>Lift</div><p>Qualified buyer appointments for U.S. real estate agents.</p></footer>
 </main>;
}
